# Generated by Django 3.2.8 on 2022-01-01 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='pictures',
            old_name='title',
            new_name='name',
        ),
    ]
