# Generated by Django 3.2.8 on 2022-01-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20220101_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='author_category',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='pictures',
            old_name='author_pictures',
            new_name='owner',
        ),
    ]
