# Generated by Django 3.2.8 on 2022-01-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_rename_pictures_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
    ]
