# Generated by Django 3.2.8 on 2022-01-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0006_rename_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Folder', max_length=300),
        ),
    ]
