# Generated by Django 3.2.8 on 2022-01-04 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0009_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='pics.category')),
            ],
        ),
    ]
