# Generated by Django 3.2.8 on 2022-01-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0011_rename_date_posted_deletepicture_date_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.ForeignKey(blank=True, default='General', on_delete=django.db.models.deletion.CASCADE, to='pics.category'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
        migrations.DeleteModel(
            name='DeletePicture',
        ),
    ]
