# Generated by Django 3.2.8 on 2022-01-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0012_auto_20220108_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
